Minor userspace build changes, keeping packages in sync.

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -10,7 +10,7 @@ AC_SUBST(pkg_name)
 # defaults (to change paths and/or executables, build parameters, etc):
 #
 #   DEBUG  OPTIMIZER  MALLOCLIB
-#   PLATFORM  DISTRIBUTION  BUILDER
+#   PLATFORM  DISTRIBUTION  INSTALL_USER  INSTALL_GROUP
 #   MAKE  CC  LD  TAR  ZIP  AWK  SED  ECHO  RPM  LIBTOOL
 #   MSGFMT  MSGMERGE  XGETTEXT
 #
@@ -47,9 +47,13 @@ test -z "$DISTRIBUTION" || pkg_distribution="$DISTRIBUTION"
 AC_SUBST(pkg_distribution)
 AC_SUBST(pkg_platform)
 
-pkg_builder=`id -u -n`@`hostname`
-test -z "$BUILDER" || pkg_builder="$BUILDER"
-AC_SUBST(pkg_builder)
+pkg_user=root
+test -z "$INSTALL_USER" || pkg_user="$INSTALL_USER"
+AC_SUBST(pkg_user)
+
+pkg_group=root
+test -z "$INSTALL_GROUP" || pkg_group="$INSTALL_GROUP"
+AC_SUBST(pkg_group)
 
 dnl check if user wants their own C compiler
 test -z "$CC" && AC_PROG_CC
@@ -118,27 +122,6 @@ test -z "$ECHO" && AC_PATH_PROG(ECHO, echo, /bin/echo)
 echo=$ECHO
 AC_SUBST(echo)
 
-dnl check if the msgfmt program is available
-test -z "$MSGFMT" && AC_CHECK_PROG(MSGFMT, msgfmt, /usr/bin/msgfmt)
-msgfmt=$MSGFMT
-AC_SUBST(msgfmt)
-
-dnl check if the msgmerge program is available
-test -z "$MSGMERGE" && AC_CHECK_PROG(MSGMERGE, msgmerge, /usr/bin/msgmerge)
-msgmerge=$MSGMERGE
-AC_SUBST(msgmerge)
-
-dnl ensure xgettext is installed
-test -z "$XGETTEXT" && AC_CHECK_PROG(XGETTEXT, xgettext, /usr/bin/xgettext)
-if test "$XGETTEXT" = ""; then
-	echo
-	echo 'FATAL ERROR: xgettext does not seem to be installed.'
-	echo $pkg_name cannot be built without a working gettext installation.
-	exit 1
-fi
-xgettext=$XGETTEXT
-AC_SUBST(xgettext)
-
 dnl ensure libtool is installed
 test -z "$LIBTOOL" && AC_PATH_PROG(LIBTOOL, libtool,,/usr/bin)
 if test "$LIBTOOL" = ""; then
@@ -162,6 +145,27 @@ AC_ARG_ENABLE(gettext,
 	enable_gettext=yes)
 test $enable_gettext = "yes" && AC_DEFINE(ENABLE_GETTEXT)
 AC_SUBST(enable_gettext)
+
+dnl check if the msgfmt, msgmerge, xgettext programs are available
+if test "$enable_gettext" = yes; then
+	test -z "$MSGFMT" && AC_CHECK_PROG(MSGFMT, msgfmt, /usr/bin/msgfmt)
+	msgfmt=$MSGFMT
+	AC_SUBST(msgfmt)
+	test -z "$MSGMERGE" && AC_CHECK_PROG(MSGMERGE, msgmerge, /usr/bin/msgmerge)
+	msgmerge=$MSGMERGE
+	AC_SUBST(msgmerge)
+
+	test -z "$XGETTEXT" && AC_CHECK_PROG(XGETTEXT, xgettext, /usr/bin/xgettext)
+	xgettext=$XGETTEXT
+	AC_SUBST(xgettext)
+
+	if test "$XGETTEXT" = ""; then
+		echo
+		echo 'FATAL ERROR: xgettext does not seem to be installed.'
+		echo $pkg_name cannot be built without a working gettext installation.
+		exit 1
+	fi
+fi
 
 dnl man pages (source)
 dnl also check if man page source is gzipped
